apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doodle-postgres-pvc
  namespace: doodle-prd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: managed
