apiVersion: v1
kind: Secret
metadata:
  name: ai-web-generator-secrets
type: Opaque
stringData:
  # Authentication (local or google)
  AUTH_TYPE: "local"
  ENABLE_ADMIN: "true"
  ADMIN_EMAIL: ""
  NOTIFICATION_EMAILS: ""
  ADMIN_PASSWORD: ""
  SESSION_SECRET: "local-dev-secret"

  # Google OAuth (Required if AUTH_TYPE=google)
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

  # SMTP Configuration (Gmail App Password)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "stephane.le@gmail.com"
  SMTP_PASSWORD: "djgzxjtlkftpnjhu"

  # Database (Remote Postgres)
  DB_TYPE: "postgres"

  # Storage (S3 / MinIO)
  STORAGE_TYPE: "local"
  S3_ENDPOINT: "minio:9000"
  S3_BUCKET: "kapsule-data"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  S3_USE_SSL: "false"

  # Redis (Optional)
  REDIS_URL: "redis://redis:6379"

  # Billing Module (Optional)
  ENABLE_BILLING: "false"
  STRIPE_SECRET_KEY: ""
  STRIPE_PUBLISHABLE_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  
  # Company Info
  COMPANY_NAME: "AI Web Generator"
  COMPANY_ADDRESS: "Paris"
  COMPANY_SIRET: ""
  COMPANY_EMAIL: "contact@aiweb.gen"  
  DB_PATH: "postgres://webgen_app:@postgres.postgres.svc.cluster.local:5432/revatisens_db?sslmode=disable"
